// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
///
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUXQo_fFjPbv3JieAqfzk_A3W1lUrqWrc',
    appId: '1:378288579729:web:648874a36c3b5204064b30',
    messagingSenderId: '378288579729',
    projectId: 'recent-it',
    authDomain: 'recent-it.firebaseapp.com',
    storageBucket: 'recent-it.appspot.com',
    measurementId: 'G-G62E3ESXZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe0AB_CAYtBFrCPVfCcrR-ktDib9iSax8',
    appId: '1:378288579729:android:8b1f448903c8e230064b30',
    messagingSenderId: '378288579729',
    projectId: 'recent-it',
    storageBucket: 'recent-it.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf-B6AbogXBbEvVJcY1_sAJ8kYf5lc-Bw',
    appId: '1:378288579729:ios:68b343c411f2acf3064b30',
    messagingSenderId: '378288579729',
    projectId: 'recent-it',
    storageBucket: 'recent-it.appspot.com',
    iosClientId:
        '378288579729-0p0mc4o7in1hjlgffbjkehs4etq09sji.apps.googleusercontent.com',
    iosBundleId: 'com.example.recentIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf-B6AbogXBbEvVJcY1_sAJ8kYf5lc-Bw',
    appId: '1:378288579729:ios:68b343c411f2acf3064b30',
    messagingSenderId: '378288579729',
    projectId: 'recent-it',
    storageBucket: 'recent-it.appspot.com',
    iosClientId:
        '378288579729-0p0mc4o7in1hjlgffbjkehs4etq09sji.apps.googleusercontent.com',
    iosBundleId: 'com.example.recentIt',
  );
}
